### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by croozeus** [quikkly/ios-sdk#2] opened 2017-07-27 11:41 UTC
I'm trying to use the Quikkly SDK for iOS (with Obj-C project). I created a sample project, integrated pods into it and made my ViewController derive from QKScanViewController. I created the override `scanViewDidRequestCameraWithStatus` method in my ViewController as well. 

The code compiles and runs on the device. However, it crashes as soon as I run it with the following error:
`
Reason: image not found`

I've already set the API key and blue-print filename in the appdelegate class:
```

    QKQuikkly.apiKey = @"MY_ACTUAL_KEY";
    QKQuikkly.blueprintFilename = @"custom_blueprint";
```

What am I doing wrong?

**Comment by greggnogg-quikkly** [comment] 2017-08-04 13:23
In the target's General tab, there is an Embedded Binaries field. Please make sure that the framework has been added there. This is usually the cause of the 'Image not found' error.

We will update the docs to ensure this step is detailed.

**Comment by greggnogg-quikkly** [comment] 2017-10-31 19:48
We are unable to reproduce this issue with the latest SDK. Please retry. Closing this issue as we have no new information or response. Any further issues please raise a new ticket and we'll be happy to help

**Closed as completed by greggnogg-quikkly** 2017-10-31 19:48 UTC
